parameters:
#    publication.example.class: SportChecked\PublicationBundle\Example

services:
#    publication.example:
#        class: %publication.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
