imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    #translator:      { fallback: "%locale%" }
    translator:       { enabled: false }
    esi:              { enabled: false }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:         ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: "%kernel.root_dir%/data/data.db3"
        # path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

parameters:
    sportchecked.publication_limit: 25
    sportchecked.board_limit: 25
    sportchecked.sports_limit: 25
    sportchecked.sports_menu_limit: 100
    sportchecked.users_limit: 25
    sportchecked.lists_limit: 25
    SportChecked.all_sports: 'all'
    SportChecked.my_sports: 'my'
    SportChecked.all_categories: 'all'
    SportChecked.all_modalities: 'all'
    SportChecked.all_lists: 'all'
    SportChecked.my_lists: 'my'
    
assetic:
    debug: %kernel.debug%
    use_controller: false
    filters:
         cssrewrite: ~
         yui_css:
                    jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.8.jar
                    apply_to: \.css$

         yui_js:
                    jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.8.jar
                    apply_to: \.js$
                    
         jpegoptim:
                    bin: /usr/bin/jpegoptim
                    strip_all: true
                    max: 60
                    apply_to: "\.jpg$"
                    
         optipng:
                    bin: /usr/local/bin/optipng
                    strip_all: true
                    max: 60
                    apply_to: "\.png$"

    twig:
         functions:
                    jpegoptim: ~
                    optipng: ~
  
    