parameters:
#    category.example.class: SportChecked\CategoryBundle\Example

services:
#    category.example:
#        class: %category.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
