parameters:
#    contact.example.class: SportChecked\ContactBundle\Example

services:
#    contact.example:
#        class: %contact.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
