parameters:
#    follower.example.class: SportChecked\FollowerBundle\Example

services:
#    follower.example:
#        class: %follower.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
